"""empty message

Revision ID: 57736476cc41
Revises: 
Create Date: 2024-10-25 16:42:57.425649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57736476cc41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_temp', sa.Float(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_temp', sa.Float(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('trend_date', sa.Date(), nullable=False),
    sa.Column('avg_temp', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_trends')
    op.drop_table('weather_summary')
    op.drop_table('daily_summary')
    op.drop_table('alerts')
    op.drop_table('alert_thresholds')
    # ### end Alembic commands ###
